package ilias.uniapp.Forms;

import ilias.uniapp.db.Connector;
import ilias.uniapp.db.University;
import javax.swing.*;
import java.awt.*;

public class CommentsForm extends JDialog {

    private University university;

    // Constructor now accepts a parent Frame
    public CommentsForm(Dialog parent, University university) {
        super(parent, true); // Set the dialog as modal
        this.university = university;
        initComponents();
        setTitle("Comments for " + university.getName()); // Set the window title to the university name
        setLocationRelativeTo(parent); // Center the dialog relative to the parent window

        // Fortwse ta hdh uparxonta sxolia gia to panepistimio
        CommentsTxt.setText(university.getComments());
    }

    private void jButtonSaveCommentsActionPerformed(java.awt.event.ActionEvent evt) {
        String comments = CommentsTxt.getText();
        if (!comments.isEmpty()) {
            university.setComments(comments); // Update the University object with the new comments
            Connector.updateUniversityComments(university); // Save to the database
        }
        dispose(); // Close the dialog after saving
    }


    public static void showCommentsForm(Dialog parent, University university) {
        java.awt.EventQueue.invokeLater(() -> {
            CommentsForm dialog = new CommentsForm(parent, university);
            dialog.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentsTxt = new javax.swing.JTextArea();
        jButtonSaveComments = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        CommentsTxt.setColumns(20);
        CommentsTxt.setRows(5);
        CommentsTxt.setToolTipText("Comments");
        jScrollPane1.setViewportView(CommentsTxt);

        jButtonSaveComments.setText("Save Comments");
        jButtonSaveComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonSaveComments)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSaveComments)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }


    // Variables declaration
    private javax.swing.JTextArea CommentsTxt;
    private javax.swing.JButton jButtonSaveComments;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
}