package ilias.uniapp.Forms;
import ilias.uniapp.json.JsonHttpRequester;

import javax.swing.*;
import java.util.List;

//klasi gia anazitisi panepistimiou vash xwras
public class CountrySearchForm extends JDialog {

    //consturctor
    public CountrySearchForm() {
        //dhmioyrghse tin forma
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        cmdSearch = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Αναζήτηση Πανεπιστημίου Βάση Χώρας");
        setBackground(new java.awt.Color(255, 102, 102));
        setModal(true);

        lblCountry.setBackground(new java.awt.Color(255, 51, 51));
        lblCountry.setText("Country's Name:");
        lblCountry.setToolTipText("");
        lblCountry.setPreferredSize(new java.awt.Dimension(300, 300));

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        cmdSearch.setText("Search");
        cmdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSearchActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //methodos gia emfanisi tis formas anazitisis vash xwras
    public static void showCountrySearchForm() {
        java.awt.EventQueue.invokeLater(() -> {
            new CountrySearchForm().setVisible(true);
        });
    }
    
    private void cmdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSearchActionPerformed
        lblError.setText("");  // Clear any previous error
        String countryName = txtCountry.getText().trim();

        if (countryName.isEmpty()) {
            lblError.setText("Παρακαλώ εισάγετε όνομα χώρας.");
            return;
        }

        //Emfanizw ta panepistimia vash xwras
        List<String> universities = JsonHttpRequester.getUniversitiesByCountry(countryName);
        if (universities!= null) {
            UniversitiesForm.showUniversitiesForm(universities);
        } else {
            lblError.setText("Το πανεπιστήμιο δεν βρέθηκε.");
        }
    }//GEN-LAST:event_cmdSearchActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        cmdSearchActionPerformed(evt);
    }//GEN-LAST:event_txtCountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSearch;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtCountry;
    // End of variables declaration//GEN-END:variables
}
