package ilias.uniapp.Forms;

import ilias.uniapp.PDF.PDFWriter;
import ilias.uniapp.db.Connector;
import ilias.uniapp.db.SortByViews;
import ilias.uniapp.db.University;

import javax.swing.*;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import java.awt.*;
import java.io.IOException;
import java.util.Collections;
import java.util.List;


public class UniversityStatsForm extends javax.swing.JDialog {

    List <University> universities;

    /**
     * Creates new form MealStatsFormNew
     */
    public UniversityStatsForm() {
        //super(parent, modal);
        initComponents();
        setTitle("Στατιστικά γευμάτων");
        setPreferredSize(new Dimension(500, 450));
        pack();

        setLocationRelativeTo(
                null);

        universities = Connector.getUniversities();
        Collections.sort(universities, new SortByViews().reversed());

        TableModel tb = new TableModel() {

            @Override
            public int getRowCount() {
                return universities.size();
            }

            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public String getColumnName(int columnIndex) {
                switch (columnIndex) {
                    case 0 -> {
                        return "Πανεπιστήμιο";
                    }
                    case 1 -> {
                        return "Προβολές";
                    }
                }
                return "";
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0 -> {
                        return String.class;
                    }
                    case 1 -> {
                        return Integer.class;
                    }
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0 -> {
                        return universities.get(rowIndex).getName();
                    }
                    case 1 -> {
                        return universities.get(rowIndex).getUniversityviews();
                    }
                }
                return "";
            }

            @Override
            public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            }

            @Override
            public void addTableModelListener(TableModelListener l) {
            }

            @Override
            public void removeTableModelListener(TableModelListener l) {
            }

        };

        jTableUniversitiesStats.setModel(tb);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonToPDF = new javax.swing.JButton();
        jScrollPaneUniversitiesStats = new javax.swing.JScrollPane();
        jTableUniversitiesStats = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Στατιστικά Πανεπιστημίων");

        jButtonToPDF.setText("Προβολή στατιστικών πανεπιστημίων σε αρχείο pdf");
        jButtonToPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToPDFActionPerformed(evt);
            }
        });

        jTableUniversitiesStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneUniversitiesStats.setViewportView(jTableUniversitiesStats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneUniversitiesStats, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonToPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneUniversitiesStats, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonToPDF)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonToPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToPDFActionPerformed

        // Δημιουργία διαλόγου αποθήκευσης
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf",
                "pdf");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle(
                "Επιλέξτε που θα αποθηκευτεί το PDF αρχείο σας");

        // Έλεγχος επιλογής χρήστη
        int userSelection = fileChooser.showSaveDialog(this);
        // Συνεχίζουμε την εκτέλεση της μεθόδου μόνο οταν ο χρήστης
        // επιλέξει "Αποθήκευση"
        if (userSelection != JFileChooser.APPROVE_OPTION) {
            return;
        }

        // Αποθηκέυουμε στην μεταβλητή path, την διαδρομή του αρχείου
        // αποθήκευσης που επίλεξε ο χρήστης
        String path = "";
        try {
            path = fileChooser.getSelectedFile().getCanonicalPath();
        } catch (IOException io) {
        }
        if (!path.isEmpty()) {
            if (PDFWriter.createPDFFile(universities, path)) {
                JOptionPane.showMessageDialog(this, "Το αρχείο pdf αποθηκεύτηκε επιτυχώς", "Αποθήκευση PDF",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonToPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void showUniversitiesStatsForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityStatsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityStatsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityStatsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityStatsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniversityStatsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonToPDF;
    private javax.swing.JScrollPane jScrollPaneUniversitiesStats;
    private javax.swing.JTable jTableUniversitiesStats;
    // End of variables declaration//GEN-END:variables
}
