/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilias.uniapp.Forms;

import ilias.uniapp.db.University;
import ilias.uniapp.json.JsonHttpRequester;

import javax.swing.*;
import java.util.List;



public class UniversitiesForm extends javax.swing.JDialog {

    private List <String> u;//metabliti pou periexei ta stoixeia kai tis allages otan xrieazetai


    public UniversitiesForm(List universityParam) {
        initComponents();

        List<String> u = universityParam;

        jListCategories.setEnabled(false);
        jListUniversities.setEnabled(false);

        List<String> universities = u;
        DefaultListModel<String> universitiesList = new DefaultListModel<>();

        for (String universityCategory : universities) {
            universitiesList.addElement(universityCategory);
        }
        jListCategories.setModel(universitiesList);
        jListCategories.setEnabled(true);

        pack();
        setLocationRelativeTo(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCountry = new javax.swing.JLabel();
        jScrollPaneCountry = new javax.swing.JScrollPane();
        jListCategories = new javax.swing.JList<>();
        jLabelUniversities = new javax.swing.JLabel();
        jScrollPaneUniversities = new javax.swing.JScrollPane();
        jListUniversities = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Πανεπιστήμια");

        jLabelCountry.setText("Keyword");
        jLabelCountry.setToolTipText("");

        jListCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCategoriesValueChanged(evt);
            }
        });
        jScrollPaneCountry.setViewportView(jListCategories);

        jLabelUniversities.setText("Πανεπιστήμια");

        jListUniversities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Uni1", "Uni2", "Uni3", "Uni4", "Uni5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListUniversities.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUniversitiesValueChanged(evt);
            }
        });
        jScrollPaneUniversities.setViewportView(jListUniversities);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUniversities)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneUniversities, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jLabelUniversities))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(jScrollPaneUniversities))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCategoriesValueChanged
        if (!evt.getValueIsAdjusting()) {
            jListUniversities.setEnabled(false);
            List<String> universities = JsonHttpRequester.getUniversities(jListCategories.getSelectedValue());
            DefaultListModel<String> universitiesPerWord = new DefaultListModel<>();

            for (String universityName : universities) {
                universitiesPerWord.addElement(universityName);
            }
            jListUniversities.setModel(universitiesPerWord);
            jListUniversities.setEnabled(true);
        }
    }//GEN-LAST:event_jListCategoriesValueChanged

    private void jListUniversitiesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUniversitiesValueChanged
        if (!evt.getValueIsAdjusting() && jListUniversities.isEnabled()) {
            String universityName = jListUniversities.getSelectedValue();
            jListUniversities.setEnabled(false);
            University university = JsonHttpRequester.getUniversity(universityName);
            if (university != null) {
                UniversityForm.showMealForm(university);
            }
            jListUniversities.setEnabled(true);
        }
    }//GEN-LAST:event_jListUniversitiesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void showCategoriesForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    public static void showUniversitiesForm(List <String> u) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversityForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversityForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversityForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversityForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UniversitiesForm(u).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelUniversities;
    private javax.swing.JList<String> jListCategories;
    private javax.swing.JList<String> jListUniversities;
    private javax.swing.JScrollPane jScrollPaneCountry;
    private javax.swing.JScrollPane jScrollPaneUniversities;
    // End of variables declaration//GEN-END:variables
}
